# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name: "gf-shop"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0

  # dao生成
  gen:
    dao:
      - link: "mysql:root:root@tcp(127.0.0.1:3306)/gf_shop"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true